---
 - name: Installing Windows softwares
   hosts: winsystems
   gather_facts: no
   tasks: 
  #  - name: installing codeblock
#      win_package: 
#       path: http://192.168.2.101/winpackages/codeblocks-20.03mingw-setup.exe
#       product_id: codeblock
#       state: present
#       arguments: /S /VERYSILENT
#       force: yes
#    - name: Installing Anaconda navigator 
#      win_package:
#       path: http://192.168.2.101/winpackages/Anaconda3-2018.12-Windows-x86_64.exe
#       product_id: Anaconda
#       arguments: /S /VERYSILENT 
 #      state: present
  #     force: yes 
  #     user_name: admin
   #    user_password: cseadmin
    - name: Installing Rstudio
      win_package:
       path: http://192.168.2.101/winpackages/RStudio-1.2.5019.exe
       product_id: Rstudio
       arguments: /S /VERYSILENT 
       state: present
       force: yes 
         
